name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.sys.os }}
    runs-on: ${{ matrix.sys.os }}
    strategy:
      fail-fast: false
      matrix:
        sys:
          - { os: windows-2019, shell: "msys2 {0}" }
          - { os: ubuntu-20.04, shell: bash }
          - { os: macos-11, shell: bash }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          install: >-
            mingw-w64-x86_64-gcc-fortran

      - name: Build wheels
        run: |
          pipx run cibuildwheel

      - name: Make wheels pythonless
        run: |
          pip install wheel>=0.40.0
          wheel tags --python-tag py3 --abi-tag none --remove ./wheelhouse/*.whl

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
